#!/bin/env bash

./scripts/require-root

lvm_group=ubuntu-vg
lvm_vol_name=cluster-brick

# Setup LVM Volume for GlusterFS Brick
./create-gluster-vol $lvm_group $lvm_vol_name 100G

# Make directory for GlusterFS brick
mkdir -p /mnt/$lvm_vol_name/gv0
