#!/bin/env bash
#
# Script to create a gluster volume on connected peers
# source: https://docs.gluster.org/en/latest/Quick-Start-Guide/Quickstart/
#

set -eu

./scripts/require-root

if [ $# -eq 0 ]
then
    echo "missing node hostnames"
    exit 1
fi

brick_name=cluster-brick
volume_name=data
brick_path=/data/$brick_name
volume_path=$brick_path/$volume_name
node_names=$@
node_count=$#
peer_mounts=

if [ ! -d $brick_path ]
then
    echo "mounted directory must exist at:" $brick_path
    exit 1
fi

for node in $node_names
do
    peer_mounts="$peer_mounts $node:$volume_path"
done

# Create & start the GlusterFS Volume
mkdir -p $volume_path
gluster volume create $volume_name replica $node_count $peer_mounts
gluster volume start $volume_name
