#!/bin/env bash
#
# source: https://docs.docker.com/engine/install/ubuntu/
#

./scripts/require-root

if [ "$(dpkg -l | awk '/docker/ {print }'|wc -l)" -ge 1 ]; then
    echo "Docker detected as installed"
    exit 0
fi

echo "## Start Docker Install ##"

# Install docker deps
apt install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    -y

# Add Docker GPD key
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Add Docker repo
echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt update

# Install Docker & Tools
apt install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y

# Ensure Docker launches on boot
systemctl enable --now docker.service
systemctl enable --now containerd.service

# Add default daemon config
mkdir -p /etc/docker/
cp skel/etc/docker/daemon.json /etc/docker/daemon.json

echo "## Finished Docker Install ##"
