#!/bin/env bash
#
# Update the system packages, may require reboot after completion
#

./scripts/require-root

echo "## Updating Packages ##"

apt update

apt full-upgrade -y

if [ -f /var/run/reboot-required ]
then
    echo "restart was required, will restart in 10 seconds..."
    sleep 10
    shutdown -r now
    exit 3
fi

echo "## Finished Package Update ##"
